---
name: API Release Minor
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: shinesolutions
          password: ${{ secrets.SHINEOPENSOURCE_GITHUB_TOKEN }}
      - uses: ./.github/actions/api-release-minor-action
      - uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.SHINEOPENSOURCE_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
